sudo: required
dist: trusty

services:
  - docker

language: rust
cache: cargo

env:
  global:
    - RUSTFLAGS=-Dwarnings

    # Versions known to work with pinned nightly for lints.
    - CLIPPY_VERSION=0.0.207

matrix:
  include:
    # Tests on all the channels
    - env: TASK=test
      rust: stable
    - env: TASK=test
      rust: beta
    - env: TASK=test
      rust: nightly

    # Execute lints with the pinned nightly we know works.
    - env: TASK=lint
      rust: nightly-2018-06-10

  # Don't block CI if a nightly is faulty
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script: |
  if [[ $TASK = "lint" ]]; then
      if ! type -p cargo-install-update; then
          cargo install --force cargo-update
      else
          cargo install-update -i cargo-update
      fi

      rustup component add rustfmt-preview
      cargo install-update -i "clippy:$CLIPPY_VERSION"
  fi

script: |
  if [[ $TASK = "lint" ]]; then
      cargo fmt -- --check && cargo clippy
  elif [[ $TASK = "test" ]]; then
      cargo build && cargo run -- prepare-local --docker-env mini && cargo test
  fi
