os: linux
dist: trusty
sudo: required
services:
  - docker

language: rust
cache: cargo

env:
  global:
    - RUSTFLAGS=-Dwarnings

matrix:
  include:

    ###########
    #  Lints  #
    ###########

    - env: TASK=lint
      rust: stable
      if: type = pull_request OR branch = auto OR branch = try

    ##################
    #  Linux builds  #
    ##################

    - env: TASK=test-linux
      rust: stable
      if: type = pull_request OR branch = auto OR branch = try

    - env: TASK=test-linux
      rust: beta
      if: branch = auto OR branch = try

    - env: TASK=test-linux
      rust: nightly
      if: branch = auto OR branch = try

  # Don't block CI if a nightly is faulty
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script: |
  if [[ -x "ci/before/${TASK}.sh" ]]; then
      bash "ci/before/${TASK}.sh"
  fi

script: |
  if [[ -x "ci/run/${TASK}.sh" ]]; then
      bash "ci/run/${TASK}.sh"
  else
      echo "Error: missing run script for task ${TASK}"
      exit 1
  fi
